/**
 * The eleven open offers shown on /offers.
 *
 * Upstream, this list is generated by `outreach/foundry/bin/build_offer_test.py`
 * from the Demand Foundry arm ledger (the generator refuses an offer without a
 * named buyer role, an organization type, a problem, a deliverable, a delivery
 * window, or a price at or above the $200 floor). Since the page moved into this
 * site it is hand-mirrored here; the generator owner should target this file
 * instead of the retired GitHub Pages `index.html`.
 *
 * Every price, buyer role, problem, question and window is copied exactly from
 * the 2026-08-05 build. The `deliverable` titles are rewritten outcome-first from
 * the ledger's build descriptions, and the `lead` sentences are hand-written
 * (the generated "For a Office Manager at a Small legal practice" template
 * produced six article errors).
 */

export interface Offer {
  /** Stable id; also the `interest` token carried to /partner. */
  slug: string;
  /** What the buyer gets, as an outcome-first title (rewritten from the arm ledger). */
  deliverable: string;
  /** Buyer role, verbatim. */
  buyerRole: string;
  /** Organization type, verbatim. */
  organizationType: string;
  /** Hand-written "For the <role> of a <organization>" sentence. */
  lead: string;
  /** The problem we think the buyer has. */
  problem: string;
  /** Exact price string, e.g. "$400 one time" or "$200 per month". */
  price: string;
  /** Delivery window in days from an agreed scope. */
  deliveryDays: number;
  /** What we would ask first. */
  questions: readonly string[];
}

export const OFFERS: readonly Offer[] = [
  {
    slug: 'law-firm-client-intake-automation',
    deliverable: 'An intake form that collects client data and drafts the case file.',
    buyerRole: 'Managing Attorney',
    organizationType: 'Legal practice handling high-volume client intakes',
    lead: 'For the managing attorney of a legal practice handling high-volume client intakes.',
    problem:
      'Potential clients drop off during the intake process because manual data collection is slow and frustrating.',
    price: '$400 one time',
    deliveryDays: 7,
    questions: [
      'What is the average time it takes to complete a new client intake from first contact to file creation?',
      'At which step in your current intake process do you lose the most potential clients?',
    ],
  },
  {
    slug: 'law-firm-intake-form-automation',
    deliverable: 'Voicemails and emails turned into intake summaries in your spreadsheet.',
    buyerRole: 'Office Manager',
    organizationType: 'Small legal practice handling civil or family law cases',
    lead: 'For the office manager of a small legal practice handling civil or family law cases.',
    problem:
      'Attorneys waste billable hours manually transcribing client intake details from voicemails and emails.',
    price: '$450 one time',
    deliveryDays: 12,
    questions: [
      'How do you currently capture initial client details during the intake phase?',
      'What specific data points are critical for your case intake summaries?',
    ],
  },
  {
    slug: 'accountant-client-document-gateway',
    deliverable: 'A secure upload link emailed to each client for tax documents.',
    buyerRole: 'Managing Partner',
    organizationType: 'CPA firm serving small business clients',
    lead: 'For the managing partner of a CPA firm serving small business clients.',
    problem:
      'Tax season bottlenecks occur because clients send financial documents via insecure email chains.',
    price: '$250 one time',
    deliveryDays: 6,
    questions: [
      'What is your current method for collecting financial documents from clients?',
      'How much time does your team spend chasing clients for missing tax forms?',
    ],
  },
  {
    slug: 'accounting-firm-doc-extraction-pipeline',
    deliverable: 'Client uploads parsed into structured spreadsheets automatically.',
    buyerRole: 'Managing Partner',
    organizationType: 'Small to mid-sized accounting practice managing client documents',
    lead: 'For the managing partner of a small to mid-sized accounting practice managing client documents.',
    problem:
      'Staff waste billable hours manually extracting data from client documents instead of focusing on high-value advisory work.',
    price: '$400 one time',
    deliveryDays: 7,
    questions: [
      'Which specific document types consume the most manual data entry time for your team?',
      'Have you evaluated any automated extraction tools that failed to meet your customization needs?',
    ],
  },
  {
    slug: 'insurance-agency-policy-renewal-tracker',
    deliverable:
      'Policy numbers and expiration dates pulled from email into one renewal dashboard.',
    buyerRole: 'Agency Owner',
    organizationType: 'Independent insurance broker managing diverse client policies',
    lead: 'For the agency owner of an independent insurance brokerage managing diverse client policies.',
    problem:
      'Agents miss renewal dates because policy expiration data is scattered across unstructured email threads.',
    price: '$300 one time',
    deliveryDays: 7,
    questions: [
      'What is your current process for tracking policy expiration dates?',
      'How many policies do you manage that require manual renewal follow-up?',
    ],
  },
  {
    slug: 'insurance-agency-renewal-sequence-bot',
    deliverable: 'An email and task sequence that starts 90 days before each renewal.',
    buyerRole: 'Agency Owner',
    organizationType: 'Independent insurance broker managing policy renewals',
    lead: 'For the agency owner of an independent insurance brokerage managing policy renewals.',
    problem:
      'Agents miss critical renewal windows because tracking 90-day outreach sequences manually is error-prone.',
    price: '$300 one time',
    deliveryDays: 4,
    questions: [
      'How do you currently track and initiate contact for policies coming up for renewal?',
      'What percentage of renewals are secured before the final 30-day window?',
    ],
  },
  {
    slug: 'mortgage-broker-doc-collection-bot',
    deliverable: 'SMS and email requests that collect loan documents into a secure folder.',
    buyerRole: 'Senior Broker',
    organizationType: 'Brokerage firm coordinating loans between buyers and lenders',
    lead: 'For a senior broker at a brokerage firm coordinating loans between buyers and lenders.',
    problem:
      'Brokers lose deal momentum chasing clients for missing income documents via disjointed phone calls and emails.',
    price: '$400 per month',
    deliveryDays: 10,
    questions: [
      'Which specific documents cause the most delays in your loan processing pipeline?',
      'How do you currently notify clients when a document is missing?',
    ],
  },
  {
    slug: 'landscaper-estimate-follow-up-system',
    deliverable: 'A follow-up that checks in on every unanswered estimate after 2 days.',
    buyerRole: 'Business Owner',
    organizationType: 'Residential or commercial landscaping service provider',
    lead: 'For the business owner of a residential or commercial landscaping service provider.',
    problem:
      'Quotes sent via email go unanswered because owners forget to manually follow up with prospects after 48 hours.',
    price: '$200 one time',
    deliveryDays: 4,
    questions: [
      'What percentage of your sent estimates currently convert to paid jobs?',
      'Do you have a standard timeline for following up on unpaid estimates?',
    ],
  },
  {
    slug: 'medical-spa-appointment-reminder-flow',
    deliverable: 'SMS and email reminders sent 48 and 24 hours before each appointment.',
    buyerRole: 'Clinic Director',
    organizationType: 'Aesthetic medicine clinic offering high-ticket treatments',
    lead: 'For the clinic director of an aesthetic medicine clinic offering high-ticket treatments.',
    problem:
      'Revenue is lost to no-shows because appointment reminders are sent inconsistently or too late.',
    price: '$200 per month',
    deliveryDays: 5,
    questions: [
      'What is your current no-show rate for scheduled treatments?',
      'How do you currently communicate appointment reminders to your clients?',
    ],
  },
  {
    slug: 'spa-salon-no-show-reduction-system',
    deliverable: 'SMS and email reminders that track which clients confirmed.',
    buyerRole: 'Salon Owner',
    organizationType: 'Appointment-based beauty and wellness business',
    lead: 'For the salon owner of an appointment-based beauty and wellness business.',
    problem:
      'Revenue is lost daily due to no-shows because current reminder methods are inconsistent or ignored.',
    price: '$200 per month',
    deliveryDays: 3,
    questions: [
      'What is your current no-show rate for appointments booked online versus by phone?',
      'Have you tried automated reminder tools that failed to reduce your no-show percentage?',
    ],
  },
  {
    slug: 'window-install-lead-response-automation',
    deliverable: 'Instant SMS and email replies that book an estimate for each lead.',
    buyerRole: 'Owner or Operations Manager',
    organizationType: 'Local home improvement contractor handling inbound leads',
    lead: 'For the owner or operations manager of a local home improvement contractor handling inbound leads.',
    problem:
      'You are losing revenue because manual scheduling and estimate coordination delays your response to customer inquiries.',
    price: '$250 one time',
    deliveryDays: 5,
    questions: [
      'How many hours per week does your team currently spend manually coordinating estimate appointments?',
      'What is your current average response time to a new web inquiry?',
    ],
  },
];

/** The contact form, with the offer attached so a reply is attributable. */
export function offerContactHref(offer: Pick<Offer, 'slug'>): string {
  return `/partner?interest=${offer.slug}`;
}
