#!/usr/bin/env python3
"""Export the generated offers page as the typed module the USTA site renders.

`index.html` is written by `outreach/foundry/bin/build_offer_test.py`; the live
/offers page is a React route in `US-Tech-Automations/USTA` that reads
`usta-react/src/website/pages/offers/data/offers.ts`. This script parses the
eleven `<article class="card">` blocks and prints that module, formatted the way
the USTA prettier config (printWidth 100, single quotes, trailing commas) would.

Usage: export_offers_ts.py [INDEX_HTML] [-o OFFERS_TS]
"""

from __future__ import annotations

import argparse
from html.parser import HTMLParser
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "index.html"
PRINT_WIDTH = 100
# prettier keeps a string on the key's line when the key is shorter than
# tabWidth + 3 characters (`slug`, `lead`); longer keys wrap when the line is
# too wide.
SHORT_KEY = 2 + 3

WHO = re.compile(r"^For an? (.+?) at an? (.+)\.$")
WITHIN = re.compile(r"within (\d+) days")
BUILT = re.compile(r"built (\d{4}-\d{2}-\d{2})")
PROBLEM_LABEL = "The problem we think you have"
PRICE_LABEL = "Price"
QUESTIONS_LABEL = "What we would ask you first"

# Hand-rewritten copy that the generated template cannot produce. Keyed by slug;
# every other offer falls back to `default_lead`.
LEAD_OVERRIDES = {
    "insurance-agency-policy-renewal-tracker": "For the agency owner of an independent insurance brokerage managing diverse client policies.",
    "insurance-agency-renewal-sequence-bot": "For the agency owner of an independent insurance brokerage managing policy renewals.",
    "mortgage-broker-doc-collection-bot": "For a senior broker at a brokerage firm coordinating loans between buyers and lenders.",
}
PROBLEM_OVERRIDES = {
    "window-install-lead-response-automation": "You are losing revenue because manual scheduling and estimate coordination delays your response to customer inquiries.",
}

HEADER = '''/**
 * The eleven open offers shown on /offers.
 *
 * Upstream, this list is generated by `outreach/foundry/bin/build_offer_test.py`
 * from the Demand Foundry arm ledger (the generator refuses an offer without a
 * named buyer role, an organization type, a problem, a deliverable, a delivery
 * window, or a price at or above the $200 floor). Since the page moved into this
 * site it is hand-mirrored here; the generator owner should target this file
 * instead of the retired GitHub Pages `index.html`.
 *
 * Every price, buyer role, deliverable and window is copied exactly from the
 * {built} build. Only the `lead` sentences are rewritten (the generated
 * "For a Office Manager at a Small legal practice" template produced six
 * article errors).
 */

export interface Offer {
  /** Stable id; also the `interest` token carried to /partner. */
  slug: string;
  /** The deliverable, verbatim from the arm ledger. */
  deliverable: string;
  /** Buyer role, verbatim. */
  buyerRole: string;
  /** Organization type, verbatim. */
  organizationType: string;
  /** Hand-written "For the <role> of a <organization>" sentence. */
  lead: string;
  /** The problem we think the buyer has. */
  problem: string;
  /** Exact price string, e.g. "$400 one time" or "$200 per month". */
  price: string;
  /** Delivery window in days from an agreed scope. */
  deliveryDays: number;
  /** What we would ask first. */
  questions: readonly string[];
}

export const OFFERS: readonly Offer[] = [
'''

FOOTER = '''];

/** The contact form, with the offer attached so a reply is attributable. */
export function offerContactHref(offer: Pick<Offer, 'slug'>): string {
  return `/partner?interest=${offer.slug}`;
}
'''


class OffersParser(HTMLParser):
    """Collect each article's slug, heading, who-line, labelled rows and built date."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.articles: list[dict] = []
        self.footer: list[str] = []
        self._article: dict | None = None
        self._text: list[str] | None = None
        self._field: str | None = None
        self._row_depth = 0
        self._row_label: str | None = None
        self._row_text: list[str] = []
        self._question: list[str] | None = None
        self._in_footer = False

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == "article" and a.get("class") == "card":
            self._article = {"slug": a.get("id", ""), "questions": []}
            self.articles.append(self._article)
            return
        if tag == "footer":
            self._in_footer = True
            return
        if self._article is None:
            return
        if tag == "h3":
            self._begin("deliverable")
        elif tag == "p" and a.get("class") == "who":
            self._begin("who")
        elif tag == "span" and a.get("class") == "lbl":
            self._begin("label")
        elif tag == "span" and a.get("class") == "price":
            self._begin("price")
        elif tag == "div" and a.get("class") == "row":
            self._row_depth = 1
            self._row_label = None
            self._row_text = []
            self._question = None
        elif tag == "div" and self._row_depth:
            self._row_depth += 1
            if self._row_label == QUESTIONS_LABEL:
                self._question = []

    def handle_endtag(self, tag):
        if tag == "article":
            self._article = None
            return
        if tag == "footer":
            self._in_footer = False
            return
        if self._article is None:
            return
        if tag in {"h3", "p", "span"} and self._field:
            text = " ".join("".join(self._text).split())
            field = self._field
            self._field = self._text = None
            if field == "label":
                self._row_label = text
            elif field == "who":
                match = WHO.match(text)
                if not match:
                    raise ValueError(f"unparseable who-line: {text!r}")
                self._article["buyerRole"], self._article["organizationType"] = match.groups()
            else:
                self._article[field] = text
        elif tag == "div" and self._row_depth:
            self._row_depth -= 1
            if self._question is not None and self._row_depth == 1:
                self._article["questions"].append(" ".join("".join(self._question).split()))
                self._question = None
            elif self._row_depth == 0:
                text = " ".join("".join(self._row_text).split())
                if self._row_label == PROBLEM_LABEL:
                    self._article["problem"] = text
                elif self._row_label == PRICE_LABEL:
                    match = WITHIN.search(text)
                    if not match:
                        raise ValueError(f"price row lacks a delivery window: {text!r}")
                    self._article["deliveryDays"] = int(match.group(1))

    def handle_data(self, data):
        if self._in_footer:
            self.footer.append(data)
        if self._text is not None:
            self._text.append(data)
        elif self._question is not None:
            self._question.append(data)
        elif self._row_depth:
            self._row_text.append(data)

    def _begin(self, field: str) -> None:
        self._field = field
        self._text = []


def article(noun: str) -> str:
    return "an" if noun[:1].lower() in "aeiou" else "a"


def lower_word(word: str) -> str:
    """Lower-case a word unless it is an acronym (`CPA`)."""
    return word if len(word) > 1 and word.isupper() else word.lower()


def default_lead(role: str, organization: str) -> str:
    """`For the <role> of a <organization>.`: the Title Case role is lowered
    word by word; the sentence-case organization only loses its capital."""
    lowered_role = " ".join(lower_word(word) for word in role.split(" "))
    head, _, tail = organization.partition(" ")
    org = lower_word(head) + (" " + tail if tail else "")
    return f"For the {lowered_role} of {article(org)} {org}."


def parse_offers(html: str) -> tuple[list[dict], str]:
    parser = OffersParser()
    parser.feed(html)
    parser.close()
    built = BUILT.search("".join(parser.footer))
    if not built:
        raise ValueError("footer lacks a `built YYYY-MM-DD` stamp")
    offers = []
    for raw in parser.articles:
        slug = raw["slug"]
        missing = [k for k in ("slug", "deliverable", "buyerRole", "organizationType", "problem", "price", "deliveryDays") if not raw.get(k)]
        if missing or len(raw["questions"]) == 0:
            raise ValueError(f"offer {slug!r} lacks {missing or ['questions']}")
        offers.append(
            {
                "slug": slug,
                "deliverable": raw["deliverable"],
                "buyerRole": raw["buyerRole"],
                "organizationType": raw["organizationType"],
                "lead": LEAD_OVERRIDES.get(slug) or default_lead(raw["buyerRole"], raw["organizationType"]),
                "problem": PROBLEM_OVERRIDES.get(slug) or raw["problem"],
                "price": raw["price"],
                "deliveryDays": raw["deliveryDays"],
                "questions": list(raw["questions"]),
            }
        )
    if not offers:
        raise ValueError("no <article class=\"card\"> blocks found")
    return offers, built.group(1)


def ts_string(value: str) -> str:
    """Quote like prettier: single quotes unless that needs more escapes."""
    quote = '"' if value.count("'") > value.count('"') else "'"
    body = value.replace("\\", "\\\\").replace(quote, "\\" + quote)
    return f"{quote}{body}{quote}"


def prop(key: str, value: str, indent: int = 4) -> str:
    one_line = f"{' ' * indent}{key}: {ts_string(value)},"
    if len(key) < SHORT_KEY or len(one_line) <= PRINT_WIDTH:
        return one_line + "\n"
    return f"{' ' * indent}{key}:\n{' ' * (indent + 2)}{ts_string(value)},\n"


def render(offers: list[dict], built: str) -> str:
    out = [HEADER.replace("{built}", built)]
    for offer in offers:
        out.append("  {\n")
        for key in ("slug", "deliverable", "buyerRole", "organizationType", "lead", "problem", "price"):
            out.append(prop(key, offer[key]))
        out.append(f"    deliveryDays: {offer['deliveryDays']},\n")
        out.append("    questions: [\n")
        for question in offer["questions"]:
            out.append(f"      {ts_string(question)},\n")
        out.append("    ],\n")
        out.append("  },\n")
    out.append(FOOTER)
    return "".join(out)


def export(index_html: Path) -> str:
    offers, built = parse_offers(index_html.read_text(encoding="utf-8"))
    return render(offers, built)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("index", nargs="?", type=Path, default=INDEX, help="generated offers page (default: repo index.html)")
    parser.add_argument("-o", "--output", type=Path, help="write the module here instead of stdout")
    args = parser.parse_args(argv)
    try:
        module = export(args.index)
    except (OSError, ValueError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    if args.output:
        args.output.write_text(module, encoding="utf-8")
        print(f"wrote {args.output}")
    else:
        sys.stdout.write(module)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
